DOMAIN = "tuya_ble_lock"

CONF_CLIENT_ID = "client_id"
CONF_CLIENT_SECRET = "client_secret"
CONF_REGION = "region"
CONF_POLL_INTERVAL = "poll_interval"

DEFAULT_REGION = "eu"
DEFAULT_POLL_INTERVAL = 60
MIN_POLL_INTERVAL = 30
MAX_POLL_INTERVAL = 300
